server:
  port: 8090

spring.datasource:
  mssql:
    username: sa
    password: sasa
    jdbc-url: jdbc:sqlserver://localhost:1433;database=Demo;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  mysql:
    username: root
    password: root
    jdbc-url: jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver

