server:
  port: 8070

mapping-items:
  MappingItems:
    - source: id
      target: code
      defaultValue:
      required: true
    - source: name
      target: message
      defaultValue:
      required: true
    - source: amount
      target: amount
      defaultValue: 0.0
      required: false
