server:
  port: 8070
spring:
  datasource:
    demo:
      username: root
      password: root
      jdbc-url: jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
    dev:
      username: sa
      password: sasa
      jdbc-url: jdbc:sqlserver://localhost:1433;database=PostLoan;
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    prod:
      username: sa
      password: sasa
      jdbc-url: jdbc:sqlserver://localhost:1433;database=PostLoan;
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


