server:
  port: 8070
spring:
  datasource:
    username: sa
    password: sasa
    url: jdbc:sqlserver://10.138.30.9:1433;database=PostLoan;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.mybatis.po
